import { Task } from '@/types/task';

export const initialTasks: Task[] = [
  {
    id: '1',
    title: 'Complete Next.js App Router Assignment',
    description: 'Build a full-stack student task tracking web application with Server Components and Tailwind CSS.',
    priority: 'High',
    status: 'Pending',
    category: 'Project',
    dueDate: '2026-08-10',
    createdAt: '2026-08-01',
  },
  {
    id: '2',
    title: 'Revise Linear Algebra Chapter 4',
    description: 'Solve practice problem set 4.2 to 4.5 on eigenvalues and vector spaces.',
    priority: 'High',
    status: 'Pending',
    category: 'Exam Prep',
    dueDate: '2026-08-05',
    createdAt: '2026-08-02',
  },
  {
    id: '3',
    title: 'Physics Mechanics Lab Report',
    description: 'Analyze experimental pendulum velocity data and plot graphs using Python/Excel.',
    priority: 'Medium',
    status: 'Completed',
    category: 'Lab Report',
    dueDate: '2026-08-03',
    createdAt: '2026-07-28',
  },
  {
    id: '4',
    title: 'Read Operating Systems Chapter 6 (Concurrency)',
    description: 'Read pages 210-245 focusing on Semaphores, Mutexes, and Deadlock Avoidance.',
    priority: 'Medium',
    status: 'Pending',
    category: 'Reading',
    dueDate: '2026-08-08',
    createdAt: '2026-08-01',
  },
  {
    id: '5',
    title: 'Submit Data Structures Homework 3',
    description: 'Implement Binary Search Tree balancing (AVL Tree) in C++ and submit zip on LMS.',
    priority: 'High',
    status: 'Completed',
    category: 'Homework',
    dueDate: '2026-08-02',
    createdAt: '2026-07-29',
  },
  {
    id: '6',
    title: 'Group Presentation Slides for Software Engineering',
    description: 'Design 10 slides summarizing agile sprint retrospective and system architecture diagram.',
    priority: 'Low',
    status: 'Pending',
    category: 'Project',
    dueDate: '2026-08-12',
    createdAt: '2026-08-02',
  },
];
